name: agar
main: io.github.alvinnorin.agar.agar
version: 1.0
author: Alvin Norin
commands:
  pos:
    description: Displays your position or teleports you to another.
    usage: "Usage: '/pos' to get current position, or '/pos x y z' to teleport to x,y,z"
  debug:
    description: Toggles your debugging status for this plugin.
    usage: /debug
  deb:
    description: Displays your bitcoin balance.
    usage: "Usage: '/btc' to get current balance."
